INSERT INTO colors (name) VALUES
('Alizarin Crimson'),
('Black Gesso'),
('Bright Red'),
('Burnt Umber'),
('Cadmium Yellow'),
('Dark Sienna'),
('Indian Red'),
('Indian Yellow'),
('Liquid Black'),
('Liquid Clear'),
('Midnight Black'),
('Phthalo Blue'),
('Phthalo Green'),
('Prussian Blue'),
('Sap Green'),
('Titanium White'),
('Van Dyke Brown'),
('Yellow Ochre');
